### ISSUE TITLE
Gulp hangs after Finished 'default'

### ISSUE THREAD

**Issue by hilocz** [uplink42/etmv2#125]
gulp
[02:31:04] Using gulpfile /srv/www/htdocs/etm/gulpfile.js
[02:31:04] Starting 'js'...
[02:31:04] Finished 'js' after 29 ms
[02:31:04] Starting 'css'...
[02:31:04] Finished 'css' after 7.98 ms
[02:31:04] Starting 'uglify'...
[02:31:04] Finished 'uglify' after 12 ms
[02:31:04] Starting 'watch'...
[02:31:04] Finished 'watch' after 91 ms
[02:31:04] Starting 'home_js'...
[02:31:04] Finished 'home_js' after 6.97 ms
[02:31:04] Starting 'home_css'...
[02:31:04] Finished 'home_css' after 3.54 ms
[02:31:04] Starting 'img'...
[02:31:04] Starting 'connect'...
[02:31:04] Finished 'connect' after 17 ms
[02:31:04] Starting 'home_fonts'...
[02:31:04] Finished 'home_fonts' after 1.33 ms
[02:31:04] Starting 'fonts'...
[02:31:04] Finished 'fonts' after 2.13 ms
[02:31:04] Server started http://localhost:8080
[02:31:04] LiveReload started on port 35729
WARN: Output exceeds 32000 characters
WARN: Output exceeds 32000 characters
WARN: Output exceeds 32000 characters
WARN: Output exceeds 32000 characters
WARN: Output exceeds 32000 characters
[02:31:43] gulp-imagemin: Minified 44 images (saved 39.5 kB - 0.9%)
[02:31:43] Finished 'img' after 39 s
[02:31:43] Starting 'default'...
[02:31:43] Finished 'default' after 5.25 Îźs

after that hangs forever.

Gulp is version 3.91, npm 3.10.10

Thanks

**Comment by uplink42** [comment]
Looks like an issue with uglifyJS to me.

I've been planning on rewriting the whole gulpfile at some point, but for now try commenting out the lines

.pipe(uglify())

 in both the js, home_js and uglify tasks

**Comment by hilocz** [comment]
The WARM messages 
....
WARN: Output exceeds 32000 characters
WARN: Output exceeds 32000 characters
WARN: Output exceeds 32000 characters
WARN: Output exceeds 32000 characters
WARN: Output exceeds 32000 characters
....

are gone, but the hang on the end is still there, 

I found this issue https://github.com/gulpjs/gulp/issues/819 , maybe is the same ?

Thanks

**Comment by uplink42** [comment]
Not sure, I haven't really had any issues with gulp before. Is it creating any files in /dist at all? As long as the default task is finished you should have everything ready.

**Comment by hilocz** [comment]
Yes, Dist folder is full of files. 
Counted 170 folders + files .

**Comment by uplink42** [comment]
Then it's working as expected. The gulp task is supposed to stay there indefinitely waiting for changes on local assets.

Are you able to start the application?

**Comment by hilocz** [comment]
Not sure if this is related, I can register, login, web interface is OK, but getting this error

Message: Trying to get property of non-object
Filename: models/Dashboard_model.php
Line Number: 118
Backtrace:

File: /pub/www/htdocs/etm/application/models/Dashboard_model.php
Line: 118
Function: _error_handler

File: /pub/www/htdocs/etm/application/controllers/Dashboard.php
Line: 50
Function: getTotalProfitsTrends

File: /pub/www/htdocs/etm/index.php
Line: 315
Function: require_once 

*****************************
This is not related I think, test user doesn't have any Contract, Transaction or Order

0
New Contracts
0
New transactions
0
New orders

**Comment by dkrotil** [comment]
And bunch of missing files like ->
/pub/www/htdocs/etm/citadeltax/dist/js/apps.js
/pub/www/htdocs/etm/marketorders/dist/js/apps.js
/pub/www/htdocs/etm/settings/index/dist/css/custom.min.css
.....

**Comment by hilocz** [comment]
But some files are missing , in nginx log is this >

/pub/htdocs/etm/dashboard/index/dist/css/custom.min.css failed (2: No such file or directory), /pub/htdocs/etm/transactions/index/dist/css/styles.min.css failed (2: No such file or directory), /pub/htdocs/etm/transactions/index/dist/css/custom.min.css failed (2: No such file or directory), /pub/htdocs/etm/transactions/index/images/favicon/favicon.ico failed (2: No such file or directory), /pub/htdocs/etm/marketorders/dist/luna/styles/styles.css failed (2: No such file or directory), /pub/htdocs/etm/marketorders/dist/js/apps.js failed (2:No such file or directory)

**Comment by uplink42** [comment]
It seems like nginx isn't getting the correct routes for codeigniter. All of those links point to the wrong folders. They are supposed to point to (assuming the root folder is /pub/htdocs/etm):

/pub/htdocs/etm/dist/***
On Apache I had an .htaccess file that rewrote these to the correct urls. You may have to fiddle with some configuration to get it working correctly. Unfortunately I don't use nginx so I can't help much here.
 
I will do some research and try to provide a working nginx config for the next version.

**Comment by hilocz** [comment]
OK, thanks, I used for nginx config link you provided me http://kbeezie.com/nginx-and-codeigniter/ , but looks like this doesn´t helped. 
And because the "hang" of gulp is working as designed, than you can close this issue :).
