### ISSUE TITLE
Some menu links throwing error 404

### ISSUE THREAD

**Issue by hilocz** [uplink42/etmv2#127]
Have spent couple of hours trying to find solution for nginx to work on all links on EMT interface, config from http://kbeezie.com/nginx-and-codeigniter/ is implemented, but doesn´t helped.

Dashboard = OK
Profit Breakdown = OK
Statistics = OK
Transactions = OK
Market Orders = not working 404
Contracts = OK
Assets = OK
Net worth Tracker = not working 404
Market Explorer = OK
Trade simulator = not working 404
Stock List = not working 404
Trade routes = not working 404
Citadel Taxes = not working 404
Settings = OK
API Key Management = not working 404

Thanks

**Comment by uplink42** [comment]
Something tells me it has to do with upper and lower casing on links. Take
a look at controller class and file names and see if they match the URL
strings. I've never had issues with this on Apache windows and Ubuntu but
nginx could do things differently.

**Comment by hilocz** [comment]
URL links are all lower case, filenames aren´t and when I renamed controller files to lower case it stopped working.

If I try to make it case insensitive with ~* , it stopps working too.

Same problem here https://forum.codeigniter.com/thread-62099.html

**Comment by hilocz** [comment]
Found workaround, on problem links changing name worked 

mv CitadelTax.php Citadeltax.php
mv MarketOrders.php Marketorders.php
mv NetworthTracker.php Networthtracker.php
mv StockLists.php Stocklists.php
mv APIKeyManagement.php Apikeymanagement.php
mv TradeRoutes.php Traderoutes.php
mv TradeSimulator.php Tradesimulator.php

all controllernames which has capital in middle of the name. Not sure if this http://stackoverflow.com/questions/7694312/rewrite-to-case-insensitive-urls-in-codeigniter-site will solve the problem without renaming the files.

**Comment by uplink42** [comment]
I have been planning on changing the routing to lowercase-only for a while
now. Will probably do it soon.

Meanwhile, I've updated the master branch with the new pre-release version.
Try it out and see how it works for you.

**Comment by hilocz** [comment]
Is there is DB schema change ?

**Comment by uplink42** [comment]
Yes, I will update the schema. The one currently in git might be outdated.

**Comment by hilocz** [comment]
Updated to master branch ( with all that npm update, gulp, etc ), now when I try login I´m getting error >

An Error Was Encountered
Unable to load the requested class: Etmsession

**Comment by uplink42** [comment]
And I'm guessing this is the lower case issue  again. In application/libraries try changing the file/class name to 'Etmsession'.

**Comment by hilocz** [comment]
Yes, you are right, it was EtmSession ... . Now the error is this >

```
An uncaught Exception was encountered
Type: Error
Message: Class 'Twig_Loader_Filesystem' not found
Filename: /pub/www/htdocs/etm/application/libraries/Twig.php
Line Number: 94
```

Solved this problem >

Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 2 installs, 0 updates, 0 removals
  - Installing twig/twig (v1.32.0): Downloading (100%)
  - Installing kenjis/codeigniter-ss-twig (v0.2.1): Downloading (100%)
Writing lock file
Generating autoload files

**Comment by hilocz** [comment]
Log still shows some errors , when I browse through menu items >

```
ERROR - 2017-04-17 16:52:12 --> Severity: error --> Exception: Argument 1 passed to Dashboard::index() must be of the type integer, string given, called in /pub/www/htdocs/etm/system/core/CodeIgniter.php on line 514 /pub/www/htdocs/etm/application/controllers/Dashboard.php 21
ERROR - 2017-04-17 16:52:18 --> Severity: error --> Exception: Argument 1 passed to Profits::index() must be of the type integer, string given, called in /pub/www/htdocs/etm/system/core/CodeIgniter.php on line 514 /pub/www/htdocs/etm/application/controllers/Profits.php 22
ERROR - 2017-04-17 16:52:21 --> Severity: error --> Exception: Argument 1 passed to Statistics::index() must be of the type integer, string given, called in /pub/www/htdocs/etm/system/core/CodeIgniter.php on line 514 /pub/www/htdocs/etm/application/controllers/Statistics.php 20
ERROR - 2017-04-17 16:52:23 --> Severity: error --> Exception: Argument 1 passed to Transactions::index() must be of the type integer, string given, called in /pub/www/htdocs/etm/system/core/CodeIgniter.php on line 514 /pub/www/htdocs/etm/application/controllers/Transactions.php 29
ERROR - 2017-04-17 16:52:24 --> Severity: error --> Exception: Argument 1 passed to Marketorders::index() must be of the type integer, string given, called in /pub/www/htdocs/etm/system/core/CodeIgniter.php on line 514 /pub/www/htdocs/etm/application/controllers/Marketorders.php 24
ERROR - 2017-04-17 16:52:26 --> Severity: error --> Exception: Argument 1 passed to Contracts::index() must be of the type integer, string given, called in /pub/www/htdocs/etm/system/core/CodeIgniter.php on line 514 /pub/www/htdocs/etm/application/controllers/Contracts.php 54
ERROR - 2017-04-17 16:52:28 --> Severity: error --> Exception: Argument 1 passed to Assets::index() must be of the type integer, string given, called in /pub/www/htdocs/etm/system/core/CodeIgniter.php on line 514 /pub/www/htdocs/etm/application/controllers/Assets.php 19
ERROR - 2017-04-17 16:52:39 --> Severity: error --> Exception: Argument 1 passed to Networthtracker::index() must be of the type integer, string given, called in /pub/www/htdocs/etm/system/core/CodeIgniter.php on line 514 /pub/www/htdocs/etm/application/controllers/Networthtracker.php 21
ERROR - 2017-04-17 16:52:45 --> Severity: error --> Exception: Argument 1 passed to Tradesimulator::index() must be of the type integer, string given, called in /pub/www/htdocs/etm/system/core/CodeIgniter.php on line 514 /pub/www/htdocs/etm/application/controllers/Tradesimulator.php 24
ERROR - 2017-04-17 16:52:48 --> Severity: error --> Exception: Argument 1 passed to Stocklists::index() must be of the type integer, string given, called in /pub/www/htdocs/etm/system/core/CodeIgniter.php on line 514 /pub/www/htdocs/etm/application/controllers/Stocklists.php 19
ERROR - 2017-04-17 16:52:50 --> Severity: error --> Exception: Argument 1 passed to Traderoutes::index() must be of the type integer, string given, called in /pub/www/htdocs/etm/system/core/CodeIgniter.php on line 514 /pub/www/htdocs/etm/application/controllers/Traderoutes.php 20
ERROR - 2017-04-17 16:52:55 --> Severity: error --> Exception: Argument 1 passed to Citadeltax::index() must be of the type integer, string given, called in /pub/www/htdocs/etm/system/core/CodeIgniter.php on line 514 /pub/www/htdocs/etm/application/controllers/Citadeltax.php 31
ERROR - 2017-04-17 16:52:58 --> Severity: error --> Exception: Argument 1 passed to Settings::index() must be of the type integer, string given, called in /pub/www/htdocs/etm/system/core/CodeIgniter.php on line 514 /pub/www/htdocs/etm/application/controllers/Settings.php 42
```

**Comment by uplink42** [comment]
Ah yes, I forgot to mention about running composer for the new template engine :)

Did you manage to get the css and js file paths working on nginx? It seems like there's a lot of subtle differences between the 2 servers. I'd really like to have a config file for it once you get it working.

**Comment by hilocz** [comment]
Looked on nginx error log and only missing file is now 

dist/img/bg-slideshow-3.jpg
