### ISSUE TITLE
CRONS

### ISSUE THREAD

**Issue by hilocz** [uplink42/etmv2#129]
There is text in readme 

Crons: There are several crons used to maintain the application. These can be found inside the /application/controllers/internal folder.

Should be these PHP scripts croned like 

`cd application/controllers/internal; php Maintenance.php >> some_log 2&>1`

?

**Comment by uplink42** [comment]
Your crons should look something like this

00 14 * * * cd /var/www/html/v2 && php index.php internal/Autoexec_outposts
00 23 * * * cd /var/www/html/v2 && php index.php internal/Autoexec_outposts
30 09 * * * cd /var/www/html/v2 && php index.php internal/Autoexec_pricedata
00 22 * * * cd /var/www/html/v2 && php index.php internal/Autoexec_pricedata
55 23 * * * cd /var/www/html/v2 && php index.php internal/Async_updater

**Comment by hilocz** [comment]
Thanks, look like DB update is needed >

```
php index.php internal/Autoexec_pricedata

Database error: A Database Error Occurred

        Error Number: 1146
        Table 'trader.fixed_prices' doesn't exist
        SELECT *
FROM `fixed_prices`
        Filename: models/internal/Autoexec_pricedata_model.php
        Line Number: 38
```

**Comment by uplink42** [comment]
I have updated master with the up to date schema and seeders.

**Comment by hilocz** [comment]
After updating schema I´m getting this error >

```
php index.php internal/Autoexec_pricedata

An uncaught Exception was encountered

Type:        Error
Message:     Call to undefined function chunk()
Filename:    /pub/www/htdocs/etm/application/models/internal/Autoexec_pricedata_model.php
Line Number: 50

Backtrace:
        File: /pub/www/htdocs/etm/application/controllers/internal/Autoexec_pricedata.php
        Line: 30
        Function: getPrices

        File: /pub/www/htdocs/etm/index.php
        Line: 315
        Function: require_once

```

**Comment by uplink42** [comment]
I've added a missing file (in application/helpers) that should solve this error. I generally don't test crons on my windows development machine which is why some files were missing from the repo.

**Comment by hilocz** [comment]
I had this file already,  not sure why, maybe I had one update from dev branch.

**Comment by uplink42** [comment]
heads up: I've just updated the file structure to only use 1 gulp file. Make sure to follow the new readme file for instructions on how to update (should be simpler now).

**Comment by hilocz** [comment]
I think I will dump whole install and DB, will start over.
