### ISSUE TITLE
After updating to current master build logs are created under user root

### ISSUE THREAD

**Issue by hilocz** [uplink42/etmv2#130]
Looks like that recent update changed under which user is created log and query file. Under 2.1 version it was web server user, now is this root.

**Comment by uplink42** [comment]
No idea why that happens. I haven't changed anything for that. Will see how it behaves on my ubuntu machine later.

**Comment by hilocz** [comment]
I deleted all files from logs folder and now are all files created as web server user, will monitor it couple days.

**Comment by hilocz** [comment]
Install from scratch, not happening again, will close that.
