### ISSUE TITLE
After updating to 2.2 error on Dashboard

### ISSUE THREAD

**Issue by hilocz** [uplink42/etmv2#159]
This error is shown as popup on Dashboard after login in and selecting user.

`DataTables warning: table id=profits-table - Ajax error. For more information about this error, please see http://datatables.net/tn/7`

and some error 500 on 
`GET /dashboard/index/v2/main/getMsgHandles HTTP/2.0" 500`

**Comment by uplink42** [comment]
Anything on the error log?

**Comment by hilocz** [comment]
Nothing in NginX log and in app log is this 

`ERROR - 2017-04-22 15:37:57 --> Severity: error --> Exception: Argument 1 passed to ValidateRequest::checkCharacterBelong() must be of the type integer, string given, called in /pub/www/htdocs/etm/application/core/MY_Controller.php on line 38 /pub/www/htdocs/etm/application/models/common/ValidateRequest.php 26`

but this is related to session problem I think

**Comment by uplink42** [comment]
Try going to `/application/models/common/ValidateRequest` and remove the "int" hinting from character_id, making it look like this:

`public function checkCharacterBelong($character_id, int $user_id, bool $json = null): bool`

**Comment by hilocz** [comment]
This character is from 2009, I changed the file, but still same error. I can send you offline , what is in session file if you want.

**Comment by uplink42** [comment]
I seem to get logged off constantly as well. My only guess is that maybe pathfinder which you have installed on the same server might be competing with the sessions somehow. 

Posting the session file won't help much I think. Also it seems like nginx is blocking the datatables requests (error 401 - url is too large).

**Comment by hilocz** [comment]
I have separated PHP FPM pools, session save path is now different too. Sessions are totally separated, even that problem is still there. Maybe problem is with additional port in URL, which is 8443.

**Comment by hilocz** [comment]
I fixed the problem with increasing 

client_header_buffer_size 8k;
large_client_header_buffers 8 16k;

parameters .

**Comment by hilocz** [comment]
It came back, the increased buffer doesn´t helped.

**Comment by hilocz** [comment]
This shows Chrome , when I login 

```
GET https://pathfinder.bandofmagnus.cz:8443/v2/main/getMsgHandles 404 (Not Found)
send @ apps.js?v=:3
ajax @ apps.js?v=:3
(anonymous) @ apps.js?v=:36
(anonymous) @ apps.js?v=:36
```

This shows Chrome , when I get that JSON error message in Developer Console 

```
GET https://pathfinder.bandofmagnus.cz:8443/Main/headerData/1425027272/0 500 (Internal Server Error)
send @ apps.js?v=15:3
ajax @ apps.js?v=15:3
(anonymous) @ apps.js?v=15:36
l @ apps.js?v=15:2
fireWith @ apps.js?v=15:2
ready @ apps.js?v=15:2
s @ apps.js?v=15:1
```

**Comment by uplink42** [comment]
Those errors are caused for the same reasons (failure to read session data, failure to authenticate resulting in lots of errors when fetching data)

I'm really out of ideas here. I remember php 7.1 changed a few things when it comes to session ids, but if you can get them working for other files, I'm not really sure what's wrong here.

**Comment by hilocz** [comment]
Have you looked on this blog http://billpatrianakos.me/blog/2013/03/22/codeigniter-session-problems/ ?

**Comment by uplink42** [comment]
I stopped using codeigniter sessions a while ago, though so that probably wouldn't help. You can try to mess around with the config settings but I don't think they'll have any effect. If you take a look at `application/libraries/etmsession` you'll see all I'm using are native php sessions. Perhaps you can fiddle with these instead,

**Comment by hilocz** [comment]
I´m not developer, can I print what is set in session ?

**Comment by uplink42** [comment]
Try adding a log_message('error', print_r($_SESSION,1)); in controllers/
login after the setSession method is called.

**Comment by hilocz** [comment]
Hi,
I managed to get working (?) Apache / PHP FPM install. It has same problem as NGINX, user will logged out with session error message. I tried to add that log_message into application/controllers/Login.php file, but can´t find setSession method.

**Comment by uplink42** [comment]
Hello

Try going to `application/config/autoload.php` and replace line 61 with this:

`$autoload['libraries'] = array('database', 'etmsession');` if it's not already there. Also I meant `$this->etmsession->setData($session_data);` not setSession, my bad.



Also are you sure the session save path has write permissions and all that? What is the output of the session files?

**Comment by hilocz** [comment]
That autoload was already there.  I looked on session files and there were two files created, at the time I logged in, on has zero byte size and in second is has this ->
`password|s:60:"$2a$10$ZOe5ZLXOT.VjXrOWWWHOjuFgJ9FWlLD7c7g6FYc1X.ORe8.jDeHWO";email|s:25:"dkrotil@nowhere.com";`

**Comment by hilocz** [comment]
I´m doing nothing and session files are created on the go ->

```
-rw------- 1 wwwrun www   0 May  1 14:58 sess_kgfjmo19itnj4gm9hatn93ru6o
-rw------- 1 wwwrun www   0 May  1 14:57 sess_do3iv119a4ep9tj1tglu0cr3ic
-rw------- 1 wwwrun www   0 May  1 14:56 sess_cr0g0rd4mhnno756lbq4jufsj6
-rw------- 1 wwwrun www 116 May  1 14:55 sess_esgi77n8c2tu66dk9lruvekd8d
-rw------- 1 wwwrun www   0 May  1 14:55 sess_djk3h0p193b9koajbdeb9c87qh
```

**Comment by uplink42** [comment]
That session file looks normal. 

It seems like you're losing the session somewhere. Try adding this in `application/core_MY_Controller`

`log_message('error', $this->user_id);` right after this: `$this->user_id = (int) $this->etmsession->get('iduser');`

Try to login from the beginning and monitor the log file. It should output your user id each page load. Also delete all stored sessions and check if the session contents are changed as you browse pages.

**Comment by hilocz** [comment]
It´s changing , after login on character selection page session file includes this ->

`username|s:11:"davidkrotil";password|s:60:"$2a$10$ZOe5ZLXOT.VjXrOWWWHOjuFgJ9FWlLD7c7g6FYc1X.ORe8.jDeHWO";email|s:25:"dkrotil@nowhere.com";start|s:19:"2017-05-01 13:31:25";iduser|s:1:"1";notice|s:7:"success";msg|s:37:"Sucessfully updated characters' data.";`

After selection of character session file contains ->

`password|s:60:"$2a$10$ZOe5ZLXOT.VjXrOWWWHOjuFgJ9FWlLD7c7g6FYc1X.ORe8.jDeHWO";email|s:25:"dkrotil@nowhere.com";`

Selecting any of menu items kiks me out , new session file contains now 

`notice|s:5:"error";msg|s:36:"Invalid session or character request";`

This is in the log file ->

```
<?php defined('BASEPATH') OR exit('No direct script access allowed'); ?>

ERROR - 2017-05-01 13:30:13 --> 0
ERROR - 2017-05-01 13:34:09 --> 1
ERROR - 2017-05-01 13:34:09 --> 1
ERROR - 2017-05-01 13:34:09 --> 0
ERROR - 2017-05-01 13:34:09 --> Severity: error --> Exception: Return value of ValidateRequest::checkCharacterBelong() must be of the type boolean, none returned /srv/www/htdocs/etm/application/models/common/ValidateRequest.php 39
ERROR - 2017-05-01 13:34:09 --> 0
ERROR - 2017-05-01 13:34:09 --> 0
ERROR - 2017-05-01 13:34:52 --> 0
ERROR - 2017-05-01 13:34:52 --> 0
ERROR - 2017-05-01 13:34:54 --> 0
```

**Comment by uplink42** [comment]
The session makes sense. It seems like the chart requests are what's kicking you out. Try this.

In application/core/MY_Controller, add this at the beginning of buildData()
`$this->user_id = 1;`

Does it kick you out when logging in?

**Comment by hilocz** [comment]
Do you mean like this ?

```
protected function buildData(int $character_id, bool $aggr, string $callback, string $model, array $configs)
    {
        $this->user_id = 1;
```
if yes, then nothing changed.

**Comment by uplink42** [comment]
Let's do a quick test

go to application/models/common/validateRequest

and comment out the checkCharacterBelong function, make it look like this:

```
public function checkCharacterBelong($character_id, int $user_id, bool $json = null): bool
    {
        /*$this->db->where('character_eve_idcharacter', $character_id);
        $this->db->where('iduser', $user_id);
        $query = $this->db->get('v_user_characters');

        if ($query->num_rows() != 0) {
            return true;
        } else if ($json) {
            echo Msg::INVALID_REQUEST;
            return false;
        } else {
            return false;
        }*/
        return true;
    }
```

**Comment by hilocz** [comment]
Started working, no more logouts and I see in API Key Management my character, this never happened before.

In log file is this error , when I browse through menu items 

`ERROR - 2017-05-01 14:46:05 --> Severity: error --> Exception: Argument 1 passed to Login_model::getCharacterName() must be of the type integer, string given, called in /pub/www/htdocs/etm/application/core/MY_Controller.php on line 107 /pub/www/htdocs/etm/application/models/Login_model.php 75`

**Comment by uplink42** [comment]
You won't be able to see any chart or tables data this way, though. The problem is that for some reason external requests (made from JS) are not getting access to your session variables. 

In application/controllers/dashboard, try adding a log to the profits table method:

```
public function getProfitTable(int $character_id, int $interval = 3, bool $aggr = false) : void
    {
        log_message('error', $this->user_id);

```
and see if you get a result of 1 or 0 here.

**Comment by hilocz** [comment]
Clicking od Dashboard produce error in browser 

DataTables warning: table id=profits-table - Invalid JSON response. For more information about this error, please see http://datatables.net/tn/1

and in log is this 

```
ERROR - 2017-05-01 14:51:23 --> 1
ERROR - 2017-05-01 14:51:23 --> 1
ERROR - 2017-05-01 14:51:23 --> Severity: error --> Exception: Argument 1 passed to Login_model::getCharacterName() must be of the type integer, string given, called in /pub/www/htdocs/etm/application/core/MY_Controller.php on line 107 /pub/www/htdocs/etm/application/models/Login_model.php 75
ERROR - 2017-05-01 14:51:24 --> 1
ERROR - 2017-05-01 14:51:24 --> 1
ERROR - 2017-05-01 14:51:24 --> 1
ERROR - 2017-05-01 14:51:24 --> 1
ERROR - 2017-05-01 14:51:24 --> Severity: Notice --> Undefined index: length /pub/www/htdocs/etm/application/models/common/Datatables.php 43
ERROR - 2017-05-01 14:51:24 --> Severity: Notice --> Undefined index: start /pub/www/htdocs/etm/application/models/common/Datatables.php 43
ERROR - 2017-05-01 14:51:24 --> Severity: Notice --> Undefined index: draw /pub/www/htdocs/etm/application/models/common/Datatables.php 99
ERROR - 2017-05-01 14:51:25 --> 0
```

**Comment by uplink42** [comment]
I just visited your install, cleared cookies and it seems to work now. I see assets, charts all working.

**Comment by hilocz** [comment]
And you don´t get the error popup ?

`DataTables warning: table id=profits-table - Invalid JSON response. For more information about this error, please see http://datatables.net/tn/1`

**Comment by uplink42** [comment]
I would update to the latest version in master to get rid of it. Everything else seems to work for me even though I only have a dummy character there.

**Comment by hilocz** [comment]
It´s updated day ago, only what I haven´t checked is DB schema. 

JSON error is only on Dashboard and Profit Breakdown menu items.

**Comment by uplink42** [comment]
Does that happen with every character? What error does it show up on logs?
