### ISSUE TITLE
Cant register or login.

### ISSUE THREAD

**Issue by Subcode** [uplink42/etmv2#205]
Hi,
I just installed everything according to the readme but im unsire if i should be connecting to port 8080 or make a symlink in the /var/www/html folder.
if i connect to port 8080 it does not load index.php but show me a directory listing.
If i make a symlink i cannot register or log in. it cant find /main/register was not found on this server. Same for login.
What am i doing wrong?
OS: Ubuntu Desktop 16.04

**Comment by uplink42** [comment]
Hello. Seems like a problem with url rewrites or your web server configuration. There should be no need to create symlinks. In Apache, the .htaccess file should take care of all routing and navigation.

**Comment by Subcode** [comment]
So i should pull the repository into /var/www/html instead of making
a.symlink? Or i should use port 8080 provided by gulp?
Gulp does not seem to support php.
The readme does not say anything about where to put the files or what to do
with apache so i am a bit confused unfortunately.

Thank you for your help,
Fabian.Schneider

**Comment by Subcode** [comment]
Thanks this helped a lot. I seem to have fixed it by enabling rewrite and
allowing htaccess files.
Please note that rewrite is not enabled by default in apache2 and the need
to enable this has not been stated on the git repository.

Thanks a lot for your help,
Fabian Schneider

**Comment by uplink42** [comment]
I did not know about that. I'll update the readme. Glad it worked out for you.
